### PR TITLE
Do not convert headers to a hash

### LINKED ISSUE #13: Accessing headers in `http` adapter classes fails
So, I tried to adapt our code to 0.7.1 and really love how it becomes a lot simpler.

That being said, I did encounter a small issue. We are using the `http` gem in Mastodon and I tried the adapters you provided.

The request adapter converts `http`'s headers into a hash. [This line here](https://github.com/nomadium/linzer/blob/4ef67741e69e50b33321d229dd8703e57242d89d/lib/linzer.rb#L62) then calls `#slice` on that to get the `signature-input` and `signature` headers.

(BTW, the adapter for responses is missing the call to `#to_h` so this call to `#slice` fails.)

The problem is that `http` keeps the header names exactly as it received them, so they may be in their uppercase variant (`Signature-Input` and `Signature`).

~~I suspect that other adapters may have the same problem.~~

This is one of the reasons that the different http libraries have an abstraction for headers and not just keep them in a hash. I think they all have facilities to access headers regardless of the notation used. I think that maybe the adapter classes should leverage that and not just return a hash.

(I fixed this temporarily by downcasing all keys in the hash, but doing this on every request seems really wasteful.)

### PR DESCRIPTION
**Pull request by oneiros**
This is my attempt to fix #13

This removes access to a full hash of headers from a `Message` (and adapter) and instead allows requesting a single header value. To access this, the internal mechanisms of `http` and `net-http` are being used, so the notation (e.g. `Signature-Input` vs. `signature-input`) does not matter. `rack` is a bit more complicated, but thankfully the necessary conversion methods already existed.

While attempting to refactor this, I noticed a discrepancy between how headers for `rack` requests and responses are handled. And indeed, `rack` stores headers for requests and responses quite differently. But [this comment here](https://github.com/rack/rack/blob/cc2e751944ffb9cf6a6f2a1d7bb5f20af12876bf/lib/rack/response.rb#L51-L53) leads me to believe, that it expects the same notation (e.g. `HTTP_SIGNATURE_INPUT` instead of just `signature-input`). I have not looked into this too closely, but judging from that comment and how some accessor methods in that class work, I believe that should be correct.

So I tried to fix this as well.

Of course this is not the only way to address the problem in #13. So if you have a different and/or better idea, feel free to discard this.

### CODE REVIEW

File: lib/linzer.rb [hunk 1]
```diff
@@ -59,7 +59,12 @@ def sign!(request_or_response, **args)
 
     def verify!(request_or_response, key: nil, no_older_than: 900)
       message = Message.new(request_or_response)
-      signature = Signature.build(message.headers.slice("signature", "signature-input"))
+      signature_headers = {}
+      %w[signature-input signature].each do |name|
+        value = message.header(name)
+        signature_headers[name] = value if value
+      end
```
Comment (oneiros) [inline lib/linzer.rb:66]: Not having a full hash means we lose the convenience of `Hash#slice`. I do not think this is a huge problem, *but* I dislike having to repeat this in the rack auth middleware.

The only alternative I could come up with, was passing the full `Linzer::Message` object to `Signature.build`. Not sure if that is something you would consider. But maybe you have another idea?

**Comment by nomadium** [comment]
Thanks for fixing this issue! 😀
